[martij196@li04e01 ~]$ cd /hpc/users/martij196
[martij196@li04e01 ~]$ ls
loci_genotyping_project
[martij196@li04e01 ~]$ cd loci_genotyping_project/
[martij196@li04e01 loci_genotyping_project]$ ls
sample_metadata_tables
[martij196@li04e01 loci_genotyping_project]$ cd sample_metadata_tables/
[martij196@li04e01 sample_metadata_tables]$ ls
20130606_sample_info.txt  find_1kg_overlap.py  HGSVC2_sample_list.txt  HPRC_PacBio_HiFi.file.index.csv  inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ python --version
Python 3.9.18
[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ qsub inspect_overlaps
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
    Project name must be specified using bsub -P.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
ERROR: Project must be 'acc_<projectName>'.
Request aborted by esub. Job not submitted.
[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447229> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ bjobs
       JOBID       USER     JOB_NAME   STAT      QUEUE  FROM_HOST    EXEC_HOST   SUBMIT_TIME    START_TIME  TIME_LEFT
   197447229  martij196 *ct_overlaps    RUN    premium    li04e01      lh06c32  Jul 31 20:14  Jul 31 20:14     0:10 L
[martij196@li04e01 sample_metadata_tables]$ bjobs
No unfinished job found
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ ls
20130606_sample_info.txt  find_1kg_overlap.py  HGSVC2_sample_list.txt  HPRC_PacBio_HiFi.file.index.csv  inspect_overlaps  overlap.err  overlap.out
[martij196@li04e01 sample_metadata_tables]$ cat overlap.out
Sender: LSF System <lsfadmin@lh06c32>
Subject: Job 197447229: <inspect_overlaps> in cluster <chimera> Exited

Job <inspect_overlaps> was submitted from host <li04e01> by user <martij196> in cluster <chimera> at Thu Jul 31 20:14:36 2025
Job was executed on host(s) <lh06c32>, in queue <premium>, as user <martij196> in cluster <chimera> at Thu Jul 31 20:14:40 2025
</hpc/users/martij196> was used as the home directory.
</hpc/users/martij196/loci_genotyping_project/sample_metadata_tables> was used as the working directory.
Started at Thu Jul 31 20:14:40 2025
Terminated at Thu Jul 31 20:14:52 2025
Results reported at Thu Jul 31 20:14:52 2025

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
#!/bin/bash
#BSUB -P acc_oscarlr
#BSUB -J inspect_overlaps
#BSUB -W 0:10
#BSUB -M 4000
#BSUB -n 1
#BSUB -o overlap.out
#BSUB -e overlap.err

module load python/3,9.18
python find_1kg_overlap.py

------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   10.98 sec.
    Max Memory :                                 28 MB
    Average Memory :                             23.50 MB
    Total Requested Memory :                     3000.00 MB
    Delta Memory :                               2972.00 MB
    Max Swap :                                   -
    Max Processes :                              6
    Max Threads :                                7
    Run time :                                   12 sec.
    Turnaround time :                            16 sec.

The output (if any) follows:



PS:

Read file <overlap.err> for stderr output of this job.

[martij196@li04e01 sample_metadata_tables]$ cat overlap.err
Lmod has detected the following error: The following module(s) are unknown:
"python/3,9.18"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "python/3,9.18"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447286> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ bjobs
       JOBID       USER     JOB_NAME   STAT      QUEUE  FROM_HOST    EXEC_HOST   SUBMIT_TIME    START_TIME  TIME_LEFT
   197447286  martij196 *ct_overlaps   PEND    premium    li04e01      -        Jul 31 20:17       -           -
[martij196@li04e01 sample_metadata_tables]$ bjobs
       JOBID       USER     JOB_NAME   STAT      QUEUE  FROM_HOST    EXEC_HOST   SUBMIT_TIME    START_TIME  TIME_LEFT
   197447286  martij196 *ct_overlaps   PEND    premium    li04e01      -        Jul 31 20:17       -           -
[martij196@li04e01 sample_metadata_tables]$ bjobs
No unfinished job found
[martij196@li04e01 sample_metadata_tables]$ bjobs
No unfinished job found
[martij196@li04e01 sample_metadata_tables]$ cat overlap.err
Lmod has detected the following error: The following module(s) are unknown:
"python/3,9.18"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "python/3,9.18"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
[martij196@li04e01 sample_metadata_tables]$ cat overlap.err
Lmod has detected the following error: The following module(s) are unknown:
"python/3,9.18"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "python/3,9.18"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ ls
20130606_sample_info.txt  find_1kg_overlap.py  HGSVC2_sample_list.txt  HPRC_PacBio_HiFi.file.index.csv  inspect_overlaps  overlap.err  overlap.out
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447323> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ bjobs
       JOBID       USER     JOB_NAME   STAT      QUEUE  FROM_HOST    EXEC_HOST   SUBMIT_TIME    START_TIME  TIME_LEFT
   197447323  martij196 *ct_overlaps    RUN    premium    li04e01      lh06c29  Jul 31 20:19  Jul 31 20:19     0:10 L
[martij196@li04e01 sample_metadata_tables]$ bjobs
No unfinished job found
[martij196@li04e01 sample_metadata_tables]$ ls
20130606_sample_info.txt  find_1kg_overlap.py  HGSVC2_sample_list.txt  HPRC_PacBio_HiFi.file.index.csv  inspect_overlaps  overlap.err  overlap.out
[martij196@li04e01 sample_metadata_tables]$ cat overlap.err
Lmod has detected the following error: The following module(s) are unknown:
"python/3,9.18"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "python/3,9.18"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447349> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ bjobs
       JOBID       USER     JOB_NAME   STAT      QUEUE  FROM_HOST    EXEC_HOST   SUBMIT_TIME    START_TIME  TIME_LEFT
   197447349  martij196 *ct_overlaps   PEND    premium    li04e01      -        Jul 31 20:20       -           -
[martij196@li04e01 sample_metadata_tables]$ bjobs
No unfinished job found
[martij196@li04e01 sample_metadata_tables]$ bjobs
No unfinished job found
[martij196@li04e01 sample_metadata_tables]$ bjobs
No unfinished job found
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447364> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap.err
Lmod has detected the following error: The following module(s) are unknown:
"python/3,9.18"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "python/3,9.18"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
Lmod has detected the following error: The following module(s) are unknown:
"python/3.9.18"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "python/3.9.18"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
Lmod has detected the following error: The following module(s) are unknown:
"python/3.9.18"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "python/3.9.18"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
[martij196@li04e01 sample_metadata_tables]$ module spider python

----------------------------------------------------------------------------
  python:
----------------------------------------------------------------------------
     Versions:
        python/2.7.9-UCS4
        python/2.7.16
        python/2.7.17-UCS4
        python/2.7.17
        python/3.4.0
        python/3.5.0
        python/3.6.2
        python/3.7.3
        python/3.8.2
        python/3.10.4
        python/3.10.14-GCC-4.8.5
        python/3.10.17
        python/3.12.5
     Other possible modules matches:
        bx_python  lsf_python_api  wxPython

----------------------------------------------------------------------------
  To find other possible module matches execute:

      $ module -r spider '.*python.*'

----------------------------------------------------------------------------
  For detailed information about a specific "python" package (including how to load the modules) use the module's full name.
  Note that names that have a trailing (E) are extensions provided by other modules.
  For example:

     $ module spider python/3.12.5
----------------------------------------------------------------------------



[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447430> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap.err
Lmod has detected the following error: The following module(s) are unknown:
"python/3,9.18"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "python/3,9.18"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
Lmod has detected the following error: The following module(s) are unknown:
"python/3.9.18"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "python/3.9.18"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
Lmod has detected the following error: The following module(s) are unknown:
"python/3.9.18"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "python/3.9.18"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 7, in <module>
    onekg = pd.read.csv(ONEKG_file, sep='\t')
AttributeError: module 'pandas' has no attribute 'read'
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 43, saw 83

[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447611> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ ls
20130606_sample_info.txt  find_1kg_overlap.py  HGSVC2_sample_list.txt  HPRC_PacBio_HiFi.file.index.csv  inspect_overlaps  overlap.err  overlap.out  overlap_vTwo.err
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vTwo.err
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample", "population"], on_bad_lines='skip')
                                                                                                                    ^
SyntaxError: positional argument follows keyword argument
[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447692> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vTwo.err
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample", "population"], on_bad_lines='skip')
                                                                                                                    ^
SyntaxError: positional argument follows keyword argument
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample"], on_bad_lines='skip')
                                                                                                      ^
SyntaxError: positional argument follows keyword argument
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447837> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vTwo.err
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample", "population"], on_bad_lines='skip')
                                                                                                                    ^
SyntaxError: positional argument follows keyword argument
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample"], on_bad_lines='skip')
                                                                                                      ^
SyntaxError: positional argument follows keyword argument
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample"], on_bad_lines='skip')
                                                                                                      ^
SyntaxError: positional argument follows keyword argument
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447945> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vTwo.err
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample", "population"], on_bad_lines='skip')
                                                                                                                    ^
SyntaxError: positional argument follows keyword argument
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample"], on_bad_lines='skip')
                                                                                                      ^
SyntaxError: positional argument follows keyword argument
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample"], on_bad_lines='skip')
                                                                                                      ^
SyntaxError: positional argument follows keyword argument
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 43, saw 83

[martij196@li04e01 sample_metadata_tables]$
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197447997> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vTwo.err
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample", "population"], on_bad_lines='skip')
                                                                                                                    ^
SyntaxError: positional argument follows keyword argument
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample"], on_bad_lines='skip')
                                                                                                      ^
SyntaxError: positional argument follows keyword argument
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 10
    hgsvc = pd.read_csv(HGSVC_file, sep='\t', header=None, names["sra", "sample"], on_bad_lines='skip')
                                                                                                      ^
SyntaxError: positional argument follows keyword argument
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 43, saw 83

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
[martij196@li04e01 sample_metadata_tables]$
[martij196@li04e01 sample_metadata_tables]$ wget https://github.com/human-pangenomics/HPRC_metadata/blob/main/data/hprc-data-explorer-tables/HPRC_PacBio_HiFi.sample.index.csv
--2025-07-31 20:49:56--  https://github.com/human-pangenomics/HPRC_metadata/blob/main/data/hprc-data-explorer-tables/HPRC_PacBio_HiFi.sample.index.csv
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘HPRC_PacBio_HiFi.sample.index.csv’

HPRC_PacBio_HiFi.sample.index.csv                       [ <=>                                                                                                              ] 865.88K  --.-KB/s    in 0.04s

2025-07-31 20:49:57 (19.7 MB/s) - ‘HPRC_PacBio_HiFi.sample.index.csv’ saved [886661]

[martij196@li04e01 sample_metadata_tables]$ ls
20130606_sample_info.txt  find_1kg_overlap.py  HGSVC2_sample_list.txt  HPRC_PacBio_HiFi.file.index.csv  HPRC_PacBio_HiFi.sample.index.csv  inspect_overlaps  overlap.err  overlap.out  overlap_vTwo.err
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ nano inspect_overlaps
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197448179> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

[martij196@li04e01 sample_metadata_tables]$
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197448246> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197448357> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 20, in <module>
    common_hgsvc = sorted(onekg_samples.intersection(hgsvc_samples))
                                                     ^^^^^^^^^^^^^
NameError: name 'hgsvc_samples' is not defined. Did you mean: 'hgvsc_samples'?
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197448395> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 20, in <module>
    common_hgsvc = sorted(onekg_samples.intersection(hgsvc_samples))
                                                     ^^^^^^^^^^^^^
NameError: name 'hgsvc_samples' is not defined. Did you mean: 'hgvsc_samples'?
[martij196@li04e01 sample_metadata_tables]$ ls
20130606_sample_info.txt  HGSVC2_sample_list.txt           HPRC_PacBio_HiFi.sample.index.csv  overlap_1KG_HGSVC.txt  overlap.err  overlap_vThree.err
find_1kg_overlap.py       HPRC_PacBio_HiFi.file.index.csv  inspect_overlaps                   overlap_1KG_HPRC.txt   overlap.out  overlap_vTwo.err
[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HGSVC.txt
HG00096
HG00097
HG00098
HG00171
HG00267
HG00269
HG00512
HG00513
HG00514
HG00731
HG00732
HG00733
HG00844
HG00851
HG00864
HG01112
HG01113
HG01114
HG01503
HG01504
HG01505
HG01571
HG01572
HG01573
HG01596
HG02009
HG02010
HG02011
HG02018
HG02019
HG02020
HG02490
HG02491
HG02492
HG02585
HG02586
HG02587
HG03006
HG03007
HG03009
HG03063
HG03064
HG03065
HG03369
HG03370
HG03371
HG03682
HG03683
HG03684
HG03721
HG03727
HG03732
NA06984
NA06989
NA12329
NA18530
NA18531
NA18534
NA18939
NA18940
NA18941
NA19036
NA19238
NA19239
NA19240
NA19440
NA19443
NA19648
NA19649
NA19650
NA19713
NA19982
NA19983
NA20508
NA20509
NA20510
NA20845
NA20846
NA20847[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HPRC.txt
[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HPRC.txt
[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HGSVC.txt
HG00096
HG00097
HG00098
HG00171
HG00267
HG00269
HG00512
HG00513
HG00514
HG00731
HG00732
HG00733
HG00844
HG00851
HG00864
HG01112
HG01113
HG01114
HG01503
HG01504
HG01505
HG01571
HG01572
HG01573
HG01596
HG02009
HG02010
HG02011
HG02018
HG02019
HG02020
HG02490
HG02491
HG02492
HG02585
HG02586
HG02587
HG03006
HG03007
HG03009
HG03063
HG03064
HG03065
HG03369
HG03370
HG03371
HG03682
HG03683
HG03684
HG03721
HG03727
HG03732
NA06984
NA06989
NA12329
NA18530
NA18531
NA18534
NA18939
NA18940
NA18941
NA19036
NA19238
NA19239
NA19240
NA19440
NA19443
NA19648
NA19649
NA19650
NA19713
NA19982
NA19983
NA20508
NA20509
NA20510
NA20845
NA20846
NA20847[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HPRC.txt
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197448792> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ ls
20130606_sample_info.txt  HGSVC2_sample_list.txt           HPRC_PacBio_HiFi.sample.index.csv  overlap_1KG_HGSVC.txt  overlap.err  overlap_vThree.err
find_1kg_overlap.py       HPRC_PacBio_HiFi.file.index.csv  inspect_overlaps                   overlap_1KG_HPRC.txt   overlap.out  overlap_vTwo.err
[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HGSVC.txt
HG00096
HG00097
HG00098
HG00171
HG00267
HG00269
HG00512
HG00513
HG00514
HG00731
HG00732
HG00733
HG00844
HG00851
HG00864
HG01112
HG01113
HG01114
HG01503
HG01504
HG01505
HG01571
HG01572
HG01573
HG01596
HG02009
HG02010
HG02011
HG02018
HG02019
HG02020
HG02490
HG02491
HG02492
HG02585
HG02586
HG02587
HG03006
HG03007
HG03009
HG03063
HG03064
HG03065
HG03369
HG03370
HG03371
HG03682
HG03683
HG03684
HG03721
HG03727
HG03732
NA06984
NA06989
NA12329
NA18530
NA18531
NA18534
NA18939
NA18940
NA18941
NA19036
NA19238
NA19239
NA19240
NA19440
NA19443
NA19648
NA19649
NA19650
NA19713
NA19982
NA19983
NA20508
NA20509
NA20510
NA20845
NA20846
NA20847[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HPRC.txt
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197449380> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HGSVC.txt
HG00096
HG00097
HG00098
HG00171
HG00267
HG00269
HG00512
HG00513
HG00514
HG00731
HG00732
HG00733
HG00844
HG00851
HG00864
HG01112
HG01113
HG01114
HG01503
HG01504
HG01505
HG01571
HG01572
HG01573
HG01596
HG02009
HG02010
HG02011
HG02018
HG02019
HG02020
HG02490
HG02491
HG02492
HG02585
HG02586
HG02587
HG03006
HG03007
HG03009
HG03063
HG03064
HG03065
HG03369
HG03370
HG03371
HG03682
HG03683
HG03684
HG03721
HG03727
HG03732
NA06984
NA06989
NA12329
NA18530
NA18531
NA18534
NA18939
NA18940
NA18941
NA19036
NA19238
NA19239
NA19240
NA19440
NA19443
NA19648
NA19649
NA19650
NA19713
NA19982
NA19983
NA20508
NA20509
NA20510
NA20845
NA20846
NA20847[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HPRC.txt
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 20, in <module>
    common_hgsvc = sorted(onekg_samples.intersection(hgsvc_samples))
                                                     ^^^^^^^^^^^^^
NameError: name 'hgsvc_samples' is not defined. Did you mean: 'hgvsc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 16, in <module>
    common_hprc = sorted(onekg_samples.intersection(hprc_samples))
                                                    ^^^^^^^^^^^^
NameError: name 'hprc_samples' is not defined. Did you mean: 'hgsvc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197451400> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 20, in <module>
    common_hgsvc = sorted(onekg_samples.intersection(hgsvc_samples))
                                                     ^^^^^^^^^^^^^
NameError: name 'hgsvc_samples' is not defined. Did you mean: 'hgvsc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 16, in <module>
    common_hprc = sorted(onekg_samples.intersection(hprc_samples))
                                                    ^^^^^^^^^^^^
NameError: name 'hprc_samples' is not defined. Did you mean: 'hgsvc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HGSVC.txt
HG00096
HG00097
HG00098
HG00171
HG00267
HG00269
HG00512
HG00513
HG00514
HG00731
HG00732
HG00733
HG00844
HG00851
HG00864
HG01112
HG01113
HG01114
HG01503
HG01504
HG01505
HG01571
HG01572
HG01573
HG01596
HG02009
HG02010
HG02011
HG02018
HG02019
HG02020
HG02490
HG02491
HG02492
HG02585
HG02586
HG02587
HG03006
HG03007
HG03009
HG03063
HG03064
HG03065
HG03369
HG03370
HG03371
HG03682
HG03683
HG03684
HG03721
HG03727
HG03732
NA06984
NA06989
NA12329
NA18530
NA18531
NA18534
NA18939
NA18940
NA18941
NA19036
NA19238
NA19239
NA19240
NA19440
NA19443
NA19648
NA19649
NA19650
NA19713
NA19982
NA19983
NA20508
NA20509
NA20510
NA20845
NA20846
NA20847[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HPRC.txt
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 20, in <module>
    common_hgsvc = sorted(onekg_samples.intersection(hgsvc_samples))
                                                     ^^^^^^^^^^^^^
NameError: name 'hgsvc_samples' is not defined. Did you mean: 'hgvsc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 16, in <module>
    common_hprc = sorted(onekg_samples.intersection(hprc_samples))
                                                    ^^^^^^^^^^^^
NameError: name 'hprc_samples' is not defined. Did you mean: 'hgsvc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
[martij196@li04e01 sample_metadata_tables]$
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197452542> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197452834> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 20, in <module>
    common_hgsvc = sorted(onekg_samples.intersection(hgsvc_samples))
                                                     ^^^^^^^^^^^^^
NameError: name 'hgsvc_samples' is not defined. Did you mean: 'hgvsc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 16, in <module>
    common_hprc = sorted(onekg_samples.intersection(hprc_samples))
                                                    ^^^^^^^^^^^^
NameError: name 'hprc_samples' is not defined. Did you mean: 'hgsvc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_id'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_id'
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197453871> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HPRC.txt
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 20, in <module>
    common_hgsvc = sorted(onekg_samples.intersection(hgsvc_samples))
                                                     ^^^^^^^^^^^^^
NameError: name 'hgsvc_samples' is not defined. Did you mean: 'hgvsc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 16, in <module>
    common_hprc = sorted(onekg_samples.intersection(hprc_samples))
                                                    ^^^^^^^^^^^^
NameError: name 'hprc_samples' is not defined. Did you mean: 'hgsvc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_id'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_id'
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197454442> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HPRC.txt
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 20, in <module>
    common_hgsvc = sorted(onekg_samples.intersection(hgsvc_samples))
                                                     ^^^^^^^^^^^^^
NameError: name 'hgsvc_samples' is not defined. Did you mean: 'hgvsc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 16, in <module>
    common_hprc = sorted(onekg_samples.intersection(hprc_samples))
                                                    ^^^^^^^^^^^^
NameError: name 'hprc_samples' is not defined. Did you mean: 'hgsvc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_id'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_id'
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197455195> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 20, in <module>
    common_hgsvc = sorted(onekg_samples.intersection(hgsvc_samples))
                                                     ^^^^^^^^^^^^^
NameError: name 'hgsvc_samples' is not defined. Did you mean: 'hgvsc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 16, in <module>
    common_hprc = sorted(onekg_samples.intersection(hprc_samples))
                                                    ^^^^^^^^^^^^
NameError: name 'hprc_samples' is not defined. Did you mean: 'hgsvc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_id'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_id'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_id'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_id'
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_id' column not found in HPRC file")
ValueError: Expected 'sample_id' column not found in HPRC file
[martij196@li04e01 sample_metadata_tables]$ head  HPRC_PacBio_HiFi.sample.index.csv






<!DOCTYPE html>
<html
  lang="en"

[martij196@li04e01 sample_metadata_tables]$ head -n 1 HPRC_PacBio_HiFi.sample.index.csv

[martij196@li04e01 sample_metadata_tables]$ less HPRC_PacBio_HiFi.sample.index.csv
[martij196@li04e01 sample_metadata_tables]$ wget https://raw.githubusercontent.com/human-pangenomics/HPRC_metadata/main/data/hprc-data-explorer-tables/HPRC_PacBio_HiFi.sample.index.csv
--2025-07-31 21:34:52--  https://raw.githubusercontent.com/human-pangenomics/HPRC_metadata/main/data/hprc-data-explorer-tables/HPRC_PacBio_HiFi.sample.index.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 691335 (675K) [text/plain]
Saving to: ‘HPRC_PacBio_HiFi.sample.index.csv.1’

HPRC_PacBio_HiFi.sample.index.csv.1                 100%[=================================================================================================================>] 675.13K  --.-KB/s    in 0.006s

2025-07-31 21:34:52 (118 MB/s) - ‘HPRC_PacBio_HiFi.sample.index.csv.1’ saved [691335/691335]

[martij196@li04e01 sample_metadata_tables]$ less HPRC_PacBio_HiFi.sample.index.csv.1
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197459291> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HGSVC.txt
HG00096
HG00097
HG00098
HG00171
HG00267
HG00269
HG00512
HG00513
HG00514
HG00731
HG00732
HG00733
HG00844
HG00851
HG00864
HG01112
HG01113
HG01114
HG01503
HG01504
HG01505
HG01571
HG01572
HG01573
HG01596
HG02009
HG02010
HG02011
HG02018
HG02019
HG02020
HG02490
HG02491
HG02492
HG02585
HG02586
HG02587
HG03006
HG03007
HG03009
HG03063
HG03064
HG03065
HG03369
HG03370
HG03371
HG03682
HG03683
HG03684
HG03721
HG03727
HG03732
NA06984
NA06989
NA12329
NA18530
NA18531
NA18534
NA18939
NA18940
NA18941
NA19036
NA19238
NA19239
NA19240
NA19440
NA19443
NA19648
NA19649
NA19650
NA19713
NA19982
NA19983
NA20508
NA20509
NA20510
NA20845
NA20846
NA20847[martij196@li04e01 sample_metadata_tacat overlap_1KG_HPRC.txt
[martij196@li04e01 sample_metadata_tables]$ cat overlap_vThree.err
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_ID' column not found in HPRC file")
ValueError: Expected 'sample_ID' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 20, in <module>
    common_hgsvc = sorted(onekg_samples.intersection(hgsvc_samples))
                                                     ^^^^^^^^^^^^^
NameError: name 'hgsvc_samples' is not defined. Did you mean: 'hgvsc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 16, in <module>
    common_hprc = sorted(onekg_samples.intersection(hprc_samples))
                                                    ^^^^^^^^^^^^
NameError: name 'hprc_samples' is not defined. Did you mean: 'hgsvc_samples'?
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 13, in <module>
    hprc = pd.read_csv(HPRC_file, sep=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 44, saw 91

Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_id'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_id'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_ID'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_ID'
Traceback (most recent call last):
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 14, in <module>
    hprc_samples = set(hprc['sample_id'].astype(str).str.strip())
                       ~~~~^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/packages/minerva-rocky9/py_packages/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'sample_id'
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_id' column not found in HPRC file")
ValueError: Expected 'sample_id' column not found in HPRC file
Traceback (most recent call last):
  File "/hpc/users/martij196/loci_genotyping_project/sample_metadata_tables/find_1kg_overlap.py", line 17, in <module>
    raise ValueError("Expected 'sample_id' column not found in HPRC file")
ValueError: Expected 'sample_id' column not found in HPRC file
[martij196@li04e01 sample_metadata_tables]$ ls
20130606_sample_info.txt  HGSVC2_sample_list.txt           HPRC_PacBio_HiFi.sample.index.csv    inspect_overlaps       overlap_1KG_HPRC.txt  overlap.out         overlap_vTwo.err
find_1kg_overlap.py       HPRC_PacBio_HiFi.file.index.csv  HPRC_PacBio_HiFi.sample.index.csv.1  overlap_1KG_HGSVC.txt  overlap.err           overlap_vThree.err
[martij196@li04e01 sample_metadata_tables]$ less HPRC_PacBio_HiFi.sample.index.csv.1
[martij196@li04e01 sample_metadata_tables]$ nano find_1kg_overlap.py
[martij196@li04e01 sample_metadata_tables]$ bsub < inspect_overlaps
Job <197460974> is submitted to default queue <premium>.
[martij196@li04e01 sample_metadata_tables]$ watch bjobs
[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HPRC.txt
HG00097
HG00099
HG00106
HG00117
HG00126
HG00128
HG00133
HG00140
HG00146
HG00232
HG00235
HG00243
HG00253
HG00258
HG00272
HG00280
HG00290
HG00320
HG00321
HG00323
HG00329
HG00344
HG00350
HG00384
HG00408
HG00423
HG00438
HG00544
HG00558
HG00597
HG00609
HG00621
HG00639
HG00642
HG00658
HG00662
HG00673
HG00701
HG00706
HG00735
HG00738
HG00741
HG00867
HG01028
HG01048
HG01071
HG01074
HG01081
HG01099
HG01106
HG01123
HG01150
HG01167
HG01175
HG01192
HG01248
HG01252
HG01255
HG01258
HG01261
HG01346
HG01358
HG01361
HG01433
HG01496
HG01530
HG01626
HG01766
HG01784
HG01785
HG01786
HG01798
HG01884
HG01891
HG01894
HG01928
HG01934
HG01940
HG01943
HG01952
HG01960
HG01969
HG01975
HG01978
HG01981
HG01993
HG02004
HG02015
HG02027
HG02040
HG02056
HG02071
HG02074
HG02083
HG02129
HG02132
HG02135
HG02148
HG02155
HG02165
HG02178
HG02257
HG02258
HG02273
HG02280
HG02293
HG02300
HG02391
HG02392
HG02451
HG02486
HG02514
HG02523
HG02559
HG02572
HG02583
HG02602
HG02615
HG02622
HG02624
HG02630
HG02647
HG02668
HG02683
HG02698
HG02717
HG02735
HG02738
HG02809
HG02841
HG02886
HG02922
HG02965
HG02976
HG02984
HG03017
HG03041
HG03050
HG03072
HG03103
HG03108
HG03130
HG03136
HG03139
HG03195
HG03209
HG03225
HG03239
HG03270
HG03343
HG03369
HG03372
HG03388
HG03445
HG03453
HG03457
HG03458
HG03470
HG03471
HG03516
HG03521
HG03540
HG03579
HG03583
HG03611
HG03654
HG03669
HG03672
HG03688
HG03704
HG03710
HG03742
HG03778
HG03784
HG03792
HG03804
HG03816
HG03831
HG03834
HG03874
HG03919
HG03927
HG03942
HG04115
HG04153
HG04157
HG04160
HG04184
HG04187
HG04199
HG04204
HG04225
HG04228
NA18505
NA18508
NA18522
NA18565
NA18570
NA18608
NA18612
NA18620
NA18747
NA18871
NA18879
NA18952
NA18971
NA18974
NA18976
NA18983
NA19012
NA19036
NA19042
NA19043
NA19087
NA19099
NA19120
NA19131
NA19159
NA19175
NA19185
NA19190
NA19338
NA19377
NA19390
NA19391
NA19443
NA19468
NA19682
NA19700
NA19703
NA19776
NA19834
NA19835
NA19909
NA20282
NA20287
NA20346
NA20752
NA20799
NA20805
NA20809
NA20818
NA20850
NA20858
NA20870
NA20905
NA21093
NA21102
NA21106
NA21110
NA21144[martij196@li04e01 sample_metadata_tables]$ cat overlap_1KG_HGSVC.txt
HG00096
HG00097
HG00098
HG00171
HG00267
HG00269
HG00512
HG00513
HG00514
HG00731
HG00732
HG00733
HG00844
HG00851
HG00864
HG01112
HG01113
HG01114
HG01503
HG01504
HG01505
HG01571
HG01572
HG01573
HG01596
HG02009
HG02010
HG02011
HG02018
HG02019
HG02020
HG02490
HG02491
HG02492
HG02585
HG02586
HG02587
HG03006
HG03007
HG03009
HG03063
HG03064
HG03065
HG03369
HG03370
HG03371
HG03682
HG03683
HG03684
HG03721
HG03727
HG03732
NA06984
NA06989
NA12329
NA18530
NA18531
NA18534
NA18939
NA18940
NA18941
NA19036
NA19238
NA19239
NA19240
NA19440
NA19443
NA19648
NA19649
NA19650
NA19713
NA19982
NA19983
NA20508
NA20509
NA20510
NA20845
NA20846
NA20847[martij196@li04e01 sample_metadata_tables]$ ls
20130606_sample_info.txt  HGSVC2_sample_list.txt           HPRC_PacBio_HiFi.sample.index.csv    inspect_overlaps       overlap_1KG_HPRC.txt  overlap.out         overlap_vTwo.err
find_1kg_overlap.py       HPRC_PacBio_HiFi.file.index.csv  HPRC_PacBio_HiFi.sample.index.csv.1  overlap_1KG_HGSVC.txt  overlap.err           overlap_vThree.err
